const $ = (s) => document.querySelector(s);
const logEl = $('#log'); let selected; let stepIndex = 0;
function token() { return authGuard.getSession()?.token; }
function log(message, type = '') { const el = document.createElement('div'); el.className = type; el.textContent = `[${new Date().toLocaleTimeString('vi-VN')}] ${message}`; logEl.prepend(el); }
function clearObservations() { ['A', 'B'].forEach(s => { $(`#observation${s}`).textContent = 'Chưa có thao tác đọc dữ liệu.'; }); }
function showObservation(session, data) { const target = $(`#observation${session}`); if (data.row) { const r = data.row; target.innerHTML = `<div class="observation-value">${r.SoKhach} khách</div><div class="observation-detail">Booking <strong>${r.MaDatPhong}</strong> · Phòng ${r.MaPhong} · ${r.TrangThai}<br>Ghi chú: ${r.GhiChu || '-'}</div>`; return; } if (data.rows) { const rows = data.rows; target.innerHTML = `<div class="observation-value">${rows.length} đơn PENDING</div><div class="observation-detail">${rows.map(r => `${r.MaDatPhong} (${r.MaPhong}, ${r.SoKhach} khách)`).join('<br>')}</div>`; } }
async function api(path, options = {}) { const res = await fetch(`/api/transaction-demo${path}`, { ...options, headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token()}`, ...(options.headers || {}) } }); const body = await res.json(); if (!res.ok || !body.success) throw new Error(body.message || 'Thao tác thất bại'); return body.data; }
async function refresh() { const state = await api('/state'); $('#stateRows').innerHTML = state.rows.map(r => `<tr><td>${r.MaDatPhong}</td><td>${r.MaPhong}</td><td>${r.SoKhach}</td><td>${r.TrangThai}</td><td>${r.GhiChu || ''}</td></tr>`).join(''); ['A', 'B'].forEach(s => $(`#status${s}`).textContent = state.activeSessions.includes(s) ? 'đang mở' : 'đã kết thúc'); return state; }
async function execute(session, name) { try { let data; if (name === 'begin') { data = await api(`/${session}/begin`, { method: 'POST', body: JSON.stringify({ isolation: $(`#isolation${session}`).value }) }); log(`${session}: BEGIN (${data.isolation})`, 'ok'); } else if (name === 'commit' || name === 'rollback') { await api(`/${session}/${name}`, { method: 'POST' }); log(`${session}: ${name.toUpperCase()}`, 'ok'); } else { const action = name.startsWith('lock') ? 'lock' : name; const id = name === 'lock2' ? 'BK-DEMO-002' : 'BK-DEMO-001'; data = await api(`/${session}/action`, { method: 'POST', body: JSON.stringify({ action, id, value: $(`#value${session}`).value }) }); if (action === 'read' || action === 'range-read') showObservation(session, data); log(`${session}: ${action} → ${JSON.stringify(data.row || data.rows || data)}`, 'ok'); } await refresh(); return { ok: true, data }; } catch (error) { log(`${session}: ${error.message}`, 'error'); await refresh().catch(() => {}); return { ok: false, error }; } }
function guide() { const step = selected.steps[stepIndex]; $('#guideTitle').textContent = selected.title; $('#guideBody').innerHTML = `<p class="step">Bước ${stepIndex + 1}</p><p>${step.text}</p>`; $('#stepCount').textContent = `${stepIndex + 1}/${selected.steps.length}`; }
function showContext() { $('#businessContext').innerHTML = `<p><strong>Vai trò:</strong> ${selected.actors}</p><p><strong>Tác vụ thực tế:</strong> ${selected.context}</p><p><strong>Hậu quả nghiệp vụ:</strong> ${selected.impact}</p>`; }
function finish() { $('#nextStepBtn').textContent = 'Đã hoàn thành'; $('#nextStepBtn').disabled = true; const result = $('#guideResult'); result.textContent = selected.result; result.className = `guide-result${selected.error ? ' error' : ''}`; result.style.display = 'block'; }
async function choose(key) { selected = scenarios[key]; stepIndex = 0; document.querySelectorAll('.scenario').forEach(b => b.classList.toggle('active', b.dataset.scenario === key)); $('#isolationA').value = selected.isolation; $('#isolationB').value = selected.isolation; $('#isolationAdvice').innerHTML = `<strong>Gợi ý để tái hiện lỗi:</strong> ${selected.isolation}. ${selected.advice} Bạn vẫn có thể đổi hai ô Isolation level trước khi chạy bước đầu tiên.`; $('#valueA').value = '3'; $('#valueB').value = '4'; clearObservations(); $('#guideResult').style.display = 'none'; $('#nextStepBtn').textContent = 'Thực hiện bước kế tiếp'; $('#nextStepBtn').disabled = true; showContext(); try { await api('/reset', { method: 'POST' }); await refresh(); log(`Đã chọn ${selected.title}; dữ liệu và hai phiên đã được reset.`, 'info'); guide(); $('#nextStepBtn').disabled = false; } catch (e) { log(e.message, 'error'); } }
async function next() { if (!selected || stepIndex >= selected.steps.length) return; $('#nextStepBtn').disabled = true; await selected.steps[stepIndex].run(); stepIndex += 1; if (stepIndex < selected.steps.length) { guide(); $('#nextStepBtn').disabled = false; } else finish(); }
const scenarios = {
 dirty: { title: 'Dirty Read — xem đơn đặt phòng chưa xác nhận', isolation: 'READ UNCOMMITTED', advice: 'Mức này cho phép B đọc thay đổi A chưa COMMIT. Trong production phải tránh mức này.', actors: 'Lễ tân A đang chỉnh booking; điều phối viên B đang kiểm tra thông tin khách.', context: 'A vừa nhận yêu cầu đổi số khách của BK-DEMO-001 nhưng chưa bấm xác nhận. B mở cùng booking để chuẩn bị phòng.', impact: 'B có thể chuẩn bị sai số lượng giường/tiện ích vì thay đổi của A có thể bị hủy.', result: 'B đã thấy số khách là 3 trước khi A ROLLBACK. Thay đổi này chưa từng được xác nhận trong CSDL, nên đây là Dirty Read.', steps: [
  { text: 'Mở transaction của lễ tân A ở mức READ UNCOMMITTED.', run: () => execute('A', 'begin') }, { text: 'A sửa BK-DEMO-001 từ 2 lên 3 khách, nhưng chưa xác nhận lưu.', run: () => execute('A', 'write') }, { text: 'Mở transaction của lễ tân B.', run: () => execute('B', 'begin') }, { text: 'B xem BK-DEMO-001 và nhìn thấy 3 khách dù A chưa COMMIT.', run: () => execute('B', 'read') }, { text: 'A hủy thao tác (ROLLBACK): số khách chính thức quay lại 2.', run: () => execute('A', 'rollback') }, { text: 'B xem lại đơn rồi ROLLBACK.', run: async () => { await execute('B', 'read'); await execute('B', 'rollback'); } }
 ] },
 nonrepeatable: { title: 'Non-repeatable Read — thông tin booking đổi giữa lúc xử lý', isolation: 'READ COMMITTED', advice: 'Mỗi lần SELECT thấy dữ liệu đã COMMIT mới nhất.', actors: 'Lễ tân A xác nhận thông tin nhận phòng; lễ tân B tiếp nhận yêu cầu đổi số khách.', context: 'A đang kiểm tra BK-DEMO-001 để sắp xếp phòng. Trong lúc đó B cập nhật số khách theo yêu cầu của khách.', impact: 'A có thể tính sức chứa hoặc tiền cọc dựa trên số liệu cũ rồi xử lý tiếp với số liệu mới.', result: 'A xem BK-DEMO-001 có 2 khách rồi thấy 4 khách trong cùng transaction sau khi B COMMIT. Đây là Non-repeatable Read.', steps: [
  { text: 'Mở transaction của lễ tân A ở mức READ COMMITTED.', run: () => execute('A', 'begin') }, { text: 'A mở chi tiết BK-DEMO-001 lần đầu: 2 khách.', run: () => execute('A', 'read') }, { text: 'Mở transaction của lễ tân B.', run: () => execute('B', 'begin') }, { text: 'B cập nhật đơn thành 4 khách rồi xác nhận lưu.', run: async () => { $('#valueB').value = '4'; await execute('B', 'write'); await execute('B', 'commit'); } }, { text: 'A xem lại BK-DEMO-001 trong transaction đang mở.', run: () => execute('A', 'read') }, { text: 'Kết thúc transaction A.', run: () => execute('A', 'commit') }
 ] },
 phantom: { title: 'Phantom Read — danh sách đơn chờ có thêm đơn mới', isolation: 'READ COMMITTED', advice: 'Mức này cho phép bản ghi mới đã COMMIT xuất hiện ở lần tìm tiếp theo.', actors: 'Điều phối viên A lập danh sách booking chờ; lễ tân B tạo booking mới.', context: 'A đang tổng hợp các đơn PENDING để phân phòng. B tiếp nhận một booking mới và xác nhận lưu trong lúc A chưa hoàn tất báo cáo.', impact: 'Danh sách mà A xử lý thay đổi giữa chừng; số lượng booking trong báo cáo không còn nhất quán.', result: 'A tìm danh sách đơn PENDING lần đầu có 3 đơn, lần sau có thêm BK-PHANTOM-B sau khi B tạo đơn mới. Đây là Phantom Read.', steps: [
  { text: 'Mở transaction của nhân viên A ở mức READ COMMITTED.', run: () => execute('A', 'begin') }, { text: 'A tìm tất cả đơn đang chờ xác nhận: có 3 đơn.', run: () => execute('A', 'range-read') }, { text: 'Mở transaction của nhân viên B.', run: () => execute('B', 'begin') }, { text: 'B tạo thêm một booking PENDING rồi xác nhận lưu.', run: async () => { await execute('B', 'insert'); await execute('B', 'commit'); } }, { text: 'A tìm lại đúng danh sách đơn PENDING.', run: () => execute('A', 'range-read') }, { text: 'Kết thúc transaction A.', run: () => execute('A', 'commit') }
 ] },
 lost: { title: 'Lost Update — hai người cùng sửa số khách', isolation: 'READ COMMITTED', advice: 'Không có khóa hoặc version check, nên hai form cũ có thể ghi đè nhau.', actors: 'Hai lễ tân cùng mở màn hình chỉnh sửa BK-DEMO-001.', context: 'A nhận yêu cầu tăng số khách lên 3. B cũng nhận cuộc gọi khác và sửa thành 4 từ cùng form đang chứa giá trị cũ là 2.', impact: 'Thay đổi của A biến mất dù A đã lưu thành công; lịch sử booking không phản ánh đúng thao tác người dùng.', result: 'A đã lưu BK-DEMO-001 thành 3 khách, nhưng B lưu thành 4 dựa trên dữ liệu cũ là 2. Thay đổi của A bị ghi đè: Lost Update.', steps: [
  { text: 'A và B cùng mở form chỉnh sửa BK-DEMO-001 mà chưa khóa đơn.', run: async () => { await execute('A', 'begin'); await execute('B', 'begin'); } }, { text: 'A đọc đơn: 2 khách.', run: () => execute('A', 'read') }, { text: 'B cũng đọc đơn: 2 khách.', run: () => execute('B', 'read') }, { text: 'A đổi số khách thành 3 và lưu.', run: async () => { $('#valueA').value = '3'; await execute('A', 'write'); await execute('A', 'commit'); } }, { text: 'B đổi thành 4 dựa trên form cũ rồi lưu.', run: async () => { $('#valueB').value = '4'; await execute('B', 'write'); await execute('B', 'commit'); } }
 ] },
 deadlock: { title: 'Deadlock — hai lễ tân xử lý hai booking ngược thứ tự', isolation: 'REPEATABLE READ', advice: 'Dùng khóa hàng SELECT ... FOR UPDATE để tạo vòng chờ thực tế.', actors: 'Hai lễ tân xử lý yêu cầu đổi phòng liên quan đến cùng hai booking.', context: 'A xử lý BK-DEMO-001 rồi cần kiểm tra BK-DEMO-002. Cùng lúc B xử lý BK-DEMO-002 rồi cần kiểm tra BK-DEMO-001.', impact: 'Cả hai yêu cầu không thể tiếp tục. InnoDB phải hủy một yêu cầu; ứng dụng thực tế cần thông báo và cho phép thử lại.', error: true, result: 'A giữ BK-DEMO-001 và chờ BK-DEMO-002; B giữ BK-DEMO-002 và chờ BK-DEMO-001. InnoDB phát hiện vòng chờ, rollback một phiên để bảo vệ dữ liệu.', steps: [
  { text: 'Mở transaction của hai lễ tân A và B.', run: async () => { await execute('A', 'begin'); await execute('B', 'begin'); } }, { text: 'A khóa BK-DEMO-001 để xử lý.', run: () => execute('A', 'lock1') }, { text: 'B khóa BK-DEMO-002 để xử lý.', run: () => execute('B', 'lock2') }, { text: 'A cần BK-DEMO-002, đồng thời B cần BK-DEMO-001. Hãy chờ kết quả từ InnoDB.', run: async () => { const p1 = execute('A', 'lock2'); await new Promise(r => setTimeout(r, 150)); const p2 = execute('B', 'lock1'); await Promise.all([p1, p2]); const state = await refresh(); for (const s of state.activeSessions) await execute(s, 'commit'); } }
 ] }
};
document.addEventListener('DOMContentLoaded', async () => { authGuard.requireAuth(['ADMIN']); clearObservations(); document.querySelectorAll('.actions button').forEach(b => b.addEventListener('click', () => execute(b.closest('.actions').dataset.session, b.dataset.action))); document.querySelectorAll('.scenario').forEach(b => b.addEventListener('click', () => choose(b.dataset.scenario))); $('#nextStepBtn').addEventListener('click', next); $('#clearLogBtn').addEventListener('click', () => { logEl.replaceChildren(); }); $('#resetBtn').addEventListener('click', async () => { try { await api('/reset', { method: 'POST' }); clearObservations(); await refresh(); log('Đã reset dữ liệu và rollback mọi phiên.', 'ok'); } catch (e) { log(e.message, 'error'); } }); try { await api('/reset', { method: 'POST' }); await refresh(); log('Sẵn sàng mô phỏng. Chọn một hiện tượng để bắt đầu.', 'info'); } catch (e) { log(e.message, 'error'); } });
